project:
  type: website
  output-dir: docs
execute:
  freeze: false  # never re-render during project render
website:
  title: "Thomas Camminady"
  navbar:
    right:
      - blog.qmd
      - datasets.qmd
      - icon: github
        href: https://github.com/thomascamminady
      - icon: linkedin
        href: https://www.linkedin.com/in/camminady/

format:
  html:
    code-fold: true
    theme:
      - cosmo
      - styles.scss



