project:
  type: website
  output-dir: docs

website:
  title: "DRTC"
  navbar:
    right:
      - sections/datasets.qmd
      - sections/about.qmd
      - icon: github
        href: https://github.com/thomascamminady
      - icon: linkedin
        href: https://www.linkedin.com/in/camminady/

format:
  html:
    theme:
      - cosmo
      - styles.scss



