project:
  type: website
  output-dir: docs
execute:
  freeze: false  # never re-render during project render
resources:
  - CNAME

website:
  title: "Dr. Thomas Camminady"
  open-graph: true

  navbar:
    right:
      - index.qmd
      - contents/blog.qmd
      - contents/datasets.qmd
      - icon: github
        href: https://github.com/thomascamminady
      - icon: linkedin
        href: https://www.linkedin.com/in/camminady/
      - icon: twitter
        href: https://twitter.com/camminady
      - icon: code
        href: https://github.com/thomascamminady/blog


format:
  html:
    code-fold: true
    code-line-numbers: true
    theme:
      - minty
      - custom.scss



