project:
  type: website

website:
  title: "DRTC"
  navbar:
    right:
      - datasets.qmd
      - about.qmd
      - icon: github
        href: https://github.com/thomascamminady
      - icon: linkedin
        href: https://www.linkedin.com/in/camminady/

format:
  html:
    theme:
      - cosmo
      - styles.scss



